### PR TITLE
Added a unit test, check offline queue in QoS 1

### PR DESCRIPTION
**Pull request by gnought**
The items in offline queue should be same as what we inserted.
However it is related to aedes-persistence. The PR https://github.com/mcollina/aedes-persistence/pull/31 will fix the CI test.

### CODE REVIEW

**Comment by mcollina** [comment]
Would you mind to bump aedes persistence?

**Comment by gnought** [comment]
The CI will pass after merging https://github.com/mcollina/aedes-persistence/pull/33

**Comment by gnought** [comment]
And this PR also requires https://github.com/mcollina/aedes-persistence/pull/32, otherwise aedes will not properly call emptyQueue

**Comment by mcollina** [comment]
Are we ready for a release of Aedes? Would you mind sending PRs to the redis and mongodb persistences updating them?

**Comment by gnought** [comment]
Which part do you want to update aedes-persistence-redis and aedes-persistence-mongodb?
Still have some PR on hands. The release could go fast if we agree on directly making changes in master branch. :)

**Comment by mcollina** [comment]
I prefer to review the changes

Il giorno mar 6 ago 2019 alle 17:27 Gnought <notifications@github.com> ha
scritto:

**Pull request merged**
