### PR TITLE
Retain false when subscriber is active

### PR DESCRIPTION
**Pull request by GavinDmello**
Fix for <a> https://github.com/mcollina/aedes/issues/110 </a>

### CODE REVIEW

**Comment by mcollina** [comment]
Can you move the test to https://github.com/mcollina/aedes/blob/master/test/basic.js?

There is no need to use `Object.assign`, I think you can alter it in place.

**Comment by GavinDmello** [comment]
@mcollina  There object is referenced from the _retained list in Aedes persistence.

**Comment by mcollina** [comment]
I think we can create a new object in `Object.assign`  in https://github.com/mcollina/aedes-persistence/blob/master/persistence.js#L34 rather than creating a new one each time.

**Comment by mcollina** [comment]
@GavinDmello the tests are failing on CI: https://travis-ci.org/mcollina/aedes/jobs/265538833#L1031-L1050

**Comment by GavinDmello** [comment]
@mcollina  Yea. I'm checking. They seem to run locally though

**Comment by mcollina** [comment]
I will land this with #131.

**Pull request merged**
