### PR TITLE
don't emit unsubscribe on client close

### PR DESCRIPTION
**Pull request by behrad**

### CODE REVIEW

**Comment by mcollina** [comment]
Good job, can you add a unit test so we do not regress?

**Comment by behrad** [comment]
sure 👍

**Comment by behrad** [comment]
covering test added @mcollina

**Comment by ilvalle** [comment]
This PR blocks any logic a custom broker can run based on clients' unsubscriptions. Which is the advantage in not firing it? And without reverting this, is there any other way to catch client unsubscriptions on close event?

**Comment by GavinDmello** [comment]
This PR just blocks unsubscriptions on a disconnects. If normal unsubscribe events are not being fired then it's an issue

**Comment by mcollina** [comment]
Ahum, I think we might have to revert this, at least partially.

IMHO we should fire `'unsubscribe'` for `clean = true` clients, but not for `clean = false`  client. Would that still work for you @behrad?

**Comment by behrad** [comment]
> we should fire 'unsubscribe' for clean = true clients, but not for clean = false  client. Would that still work for you @behrad?

Yes, I believe we should fire unsubscribe only for clean=true clients.

**Comment by mcollina** [comment]
@behrad would you mind firing a PR?

**Pull request merged**
