### PR TITLE
remove parallel and use outgoingEnqueueCombi

### PR DESCRIPTION
**Pull request by behrad**

### CODE REVIEW

**Comment by behrad** [comment]
this is using https://github.com/mcollina/aedes-persistence/pull/13 & https://github.com/mcollina/aedes-persistence-redis/pull/39

**Comment by behrad** [comment]
> outgoingEnqueueCombi  would need to be implemented in all persistences, correct?

I would put it in CachedPersistence, are you ok with this?

**Comment by mcollina** [comment]
👍

**Comment by behrad** [comment]
https://github.com/mcollina/aedes-cached-persistence/pull/9 @mcollina

**Comment by behrad** [comment]
this is now OK to go @mcollina :muscle:

**Comment by behrad** [comment]
Is there anything blocking this PR @mcollina to be merged?

**Comment by mcollina** [comment]
I'd like to have all persistences ported to the latest aedes-persistence/aedes-cached-persistence.

**Comment by behrad** [comment]
This seems to need a rebase !

**Comment by mcollina** [comment]
Something is a bit weird with github, could you rebase?

**Comment by behrad** [comment]
I rebased the same PR, do you want me to create a new one?

**Comment by behrad** [comment]
in favor of https://github.com/mcollina/aedes/pull/152

**Pull request closed without merging**
